### ISSUE TITLE
Extract markdown support into separate plugin addon

### ISSUE THREAD

**Issue by chrislopresto** [chrislopresto/ember-freestyle#14]
So as to make remarkable dependency optional

**Comment by mszoernyi** [comment]
Where would I start doing this? And do we need to take care of nested addons? eg. `Consuming App` -> `some-addon` -> `ember-freestyle`

If I understood this [issue](https://github.com/ember-cli/ember-cli/issues/3718#issuecomment-104975924) correctly, the included hook seems to fails for nested addons due to the missing context.
